workspace:
  base: /community
  path: /${DRONE_REPO_SLUG}/
pipeline:

  build-bzt:
    image: docker.faavne.no/bzone/bztools:latest
    group: build
    pull: true
    when:
      event:
        - tag

    commands: 
      - mkdir /tmp/files
      - mkdir /tmp/lua
      - mkdir /tmp/bzmoon
      - cd /tmp/lua
      - curl -O https://raw.githubusercontent.com/bjornbytes/RxLua/master/rx.lua
      - cd /tmp/bzmoon
      - curl -O https://media.faavne.no/bzmoon/bzmoon_latest.zip
      - unzip bzmoon_latest.zip
      - mv ./bzutils.lua /tmp/lua
      - find /community/projects/bzt-pack -type f \( -name "*.lua" -o -name "*.squish" \) -exec cp {} /tmp/lua \;
      - find /community/projects/shared -type f -name "*.lua" -exec cp {} /tmp/lua \;
      - find /community/projects/shared -type f -not -name "*.lua" -exec cp {} /tmp/files \;
      - python3 /bztools/luaSquish.py /tmp/lua -r
      - find /community/projects/bzt-pack -not -ipath '*/\.*' -not -name '*.lua' -not -name '*.bin' -not -name '*.tmp' -not -name '*.py' -type f -exec cp {} /tmp/files \;
      - find /tmp/lua -name '*.lua' -type f -exec mv {} /tmp/files \;
      - python3 /bztools/crlf_fixer.py /tmp/files
      - mkdir -p /community/projects/build-output
      - mv /tmp/files /tmp/bzt-pack
      - cd /tmp
      - zip -r /community/projects/build-output/bzt17-bundle.zip ./1196613614

  build-halloween:
    image: docker.faavne.no/bzone/bztools:latest
    
    group: build
    pull: true
    when:
      event:
        - tag

    commands: 
      - mkdir /tmp/files
      - mkdir /tmp/lua
      - mkdir /tmp/bzmoon
      - cd /tmp/lua
      - curl -O https://raw.githubusercontent.com/bjornbytes/RxLua/master/rx.lua
      - cd /tmp/bzmoon
      - curl -O https://media.faavne.no/bzmoon/bzmoon_latest.zip
      - unzip bzmoon_latest.zip
      - mv ./bzutils.lua /tmp/lua
      - find /community/projects/halloween-pack -type f \( -name "*.lua" -o -name "*.squish" \) -exec cp {} /tmp/lua \;
      - find /community/projects/shared -type f -name "*.lua" -exec cp {} /tmp/lua \;
      - find /community/projects/shared -type f -not -name "*.lua" -exec cp {} /tmp/files \;
      - python3 /bztools/luaSquish.py /tmp/lua -r
      - find /community/projects/halloween-pack -not -ipath '*/\.*' -not -name '*.lua' -not -name '*.bin' -type f -exec cp {} /tmp/files \;
      - find /tmp/lua -name '*.lua' -type f -exec mv {} /tmp/files \;
      - python3 /bztools/crlf_fixer.py /tmp/files
      - mkdir -p /community/projects/build-output
      - mv /tmp/files /tmp/731940591
      - cd /tmp
      - zip -r /community/projects/build-output/halloween-bundle.zip ./731940591

  release:
    group: deploy
    image: docker.faavne.no/bzone/bztools:latest
    when:
      event:
        - tag
    commands:
      - \cp -f /community/projects/build-output/halloween-bundle.zip /drone/deploy/bz-halloween/bz-halloween_${DRONE_TAG}.zip || true
      - \cp -f /community/projects/build-output/bzt17-bundle.zip /drone/deploy/bzt-2017/bzt17_${DRONE_TAG}.zip || true
    volumes:
      - /mnt/nginx-fs/files/public/bz-community:/drone/deploy
