workspace:
  base: /bz-community/projects
  path: src/${DRONE_REPO_SLUG}

pipeline:
  pre-process:
    image: docker.faavne.no/bzone/bztools:latest
    pull: true
    when:
      event:
        - tag

    commands: 
      - mkdir /tmp/files
      - mkdir /tmp/lua
      - mkdir /tmp/bzmoon
      - cd /tmp/lua
      - curl -O https://raw.githubusercontent.com/bjornbytes/RxLua/master/rx.lua
      - cd /tmp/bzmoon
      - curl -O https://media.faavne.no/bzmoon/bzmoon_latest.zip
      - unzip bzmoon_latest.zip
      - mv ./bzutils.lua /tmp/lua
      - find /projects/halloween-pack -type f \( -name "*.lua" -o -name "*.squish" \) -exec cp {} /tmp/lua \;
      - find /projects/shared -type f -exec cp {} /tmp/lua \;
      - python3 /bztools/luaSquish.py /tmp/lua -r
      - find /projects/halloween-pack -not -ipath '*/\.*' -not -name '*.lua' -not -name '*.bin' -type f -exec cp {} /tmp/files \;
      - find /tmp/lua -name '*.lua' -type f -exec mv {} /tmp/files \;
      - python3 /bztools/crlf_fixer.py /tmp/files
      - mkdir -p /projects/build-output
      - zip -j -r /projects/build-ouput/halloween-bundle.zip /tmp/files

  release:
    group: deploy
    image: docker.faavne.no/bzone/bztools:latest
    when:
      event:
        - tag
    commands:
      - \cp -f /projects/build-ouput/halloween-bundle.zip /drone/deploy/bz-halloween/bz-halloween_${DRONE_TAG}.zip || true
    volumes:
      - /root/studynator/nginx-fs/public/bz-community:/drone/deploy
