workspace:
  path: /community

kind: pipeline
name: default

steps:
- name: build-bzt
  image: thejanne/bztools:latest
  when:
    event:
      - tag

  commands: 
    - mkdir /tmp/files
    - mkdir /tmp/lua
    - mkdir /tmp/bzmoon
    - cd /tmp/lua
    - curl -O https://raw.githubusercontent.com/bjornbytes/RxLua/master/rx.lua
    - cd /tmp/bzmoon
    - curl -O https://buildstorage.s3.nl-ams.scw.cloud/battlezone/bzmoon/build/bzmoon_bzr_v3.2.9.zip
    - unzip bzmoon_bzr_v3.2.9.zip
    - mv ./bzindex.lua /tmp/lua
    - find /community/projects/bzt-pack -type f \( -name "*.lua" -o -name "*.squish" \) -exec cp {} /tmp/lua \;
    - find /community/projects/shared -type f -name "*.lua" -exec cp {} /tmp/lua \;
    - find /community/projects/shared -type f -not -name "*.lua" -exec cp {} /tmp/files \;
    - python3 /bztools/luaSquish.py /tmp/lua -r
    - find /community/projects/bzt-pack -not -ipath '*/\.*' -not -name '*.lua' -not -name '*.bin' -not -name '*.tmp' -not -name '*.py' -type f -exec cp {} /tmp/files \;
    - find /tmp/lua -name '*.lua' -type f -exec mv {} /tmp/files \;
    - python3 /bztools/crlf_fixer.py /tmp/files
    - mkdir -p /community/bzt-pack/build
    - mv /tmp/bzmoon/*.pvdf /tmp/files
    - mv /tmp/files /tmp/1196613614
    - cd /tmp
    - zip -r /community/bzt-pack/build/bzt17-${DRONE_TAG}.zip ./1196613614
    - cp /community/bzt-pack/build/bzt17_${DRONE_TAG}.zip /community/bzt-pack/build/bzt17_latest.zip

- name: upload
  image: plugins/s3
  settings:
    bucket: buildstorage
    access_key:
      from_secret: access_key
    secret_key:
      from_secret: secret_key
    source: /community/bzt-pack/build/*.zip
    target: /battlezone/
    acl: public-read
    endpoint: https://s3.nl-ams.scw.cloud
    region: nl-ams
  when:
    event:
      - tag