workspace:
  base: /community
  path: /${DRONE_REPO_SLUG}/
pipeline:

  build-bzt:
    image: docker.faavne.no/bzone/bztools:latest
    group: build
    pull: true
    secrets: [steam_username, steam_password]
    when:
      event:
        - tag

    commands: 
      - mkdir /tmp/files
      - mkdir /tmp/lua
      - mkdir /tmp/bzmoon
      - cd /tmp/lua
      - curl -O https://raw.githubusercontent.com/bjornbytes/RxLua/master/rx.lua
      - cd /tmp/bzmoon
      - curl -O https://media.faavne.no/bzmoon/bzmoon_latest.zip
      - unzip bzmoon_latest.zip
      - mv ./bzutils.lua /tmp/lua
      - find /community/projects/bzt-pack -type f \( -name "*.lua" -o -name "*.squish" \) -exec cp {} /tmp/lua \;
      - find /community/projects/shared -type f -name "*.lua" -exec cp {} /tmp/lua \;
      - find /community/projects/shared -type f -not -name "*.lua" -exec cp {} /tmp/files \;
      - python3 /bztools/luaSquish.py /tmp/lua -r
      - find /community/projects/bzt-pack -not -ipath '*/\.*' -not -name '*.lua' -not -name '*.bin' -not -name '*.tmp' -not -name '*.py' -type f -exec cp {} /tmp/files \;
      - find /tmp/lua -name '*.lua' -type f -exec mv {} /tmp/files \;
      - python3 /bztools/crlf_fixer.py /tmp/files
      - mkdir -p /community/projects/build-output
      - mv /tmp/files /tmp/1196613614
      - cd /tmp
      - zip -r /community/projects/build-output/bzt17-bundle.zip ./1196613614
      - python3 /bztools/uploadKVFile.py $${STEAM_USERNAME} $${STEAM_PASSWORD} /community/projects/bzt-pack/.bzt-pack.vdf -contentfolder /tmp/1196613614 -changenote ${DRONE_TAG} -title ${DRONE_TAG}

  build-halloween:
    image: docker.faavne.no/bzone/bztools:latest
    
    group: build
    pull: true
    when:
      event:
        - tag

    commands: 
      - mkdir /tmp/files
      - mkdir /tmp/lua
      - mkdir /tmp/bzmoon
      - cd /tmp/lua
      - curl -O https://raw.githubusercontent.com/bjornbytes/RxLua/master/rx.lua
      - cd /tmp/bzmoon
      - curl -O https://media.faavne.no/bzmoon/bzmoon_latest.zip
      - unzip bzmoon_latest.zip
      - mv ./bzutils.lua /tmp/lua
      - find /community/projects/halloween-pack -type f \( -name "*.lua" -o -name "*.squish" \) -exec cp {} /tmp/lua \;
      - find /community/projects/shared -type f -name "*.lua" -exec cp {} /tmp/lua \;
      - find /community/projects/shared -type f -not -name "*.lua" -exec cp {} /tmp/files \;
      - python3 /bztools/luaSquish.py /tmp/lua -r
      - find /community/projects/halloween-pack -not -ipath '*/\.*' -not -name '*.lua' -not -name '*.bin' -type f -exec cp {} /tmp/files \;
      - find /tmp/lua -name '*.lua' -type f -exec mv {} /tmp/files \;
      - python3 /bztools/crlf_fixer.py /tmp/files
      - mkdir -p /community/projects/build-output
      - mv /tmp/files /tmp/731940591
      - cd /tmp
      - zip -r /community/projects/build-output/halloween-bundle.zip ./731940591

  upload:
    image: appleboy/drone-scp
    host: faavne.no
    username: root
    secrets: [ssh_key]
    key_path: /ssh/id_rsa
    target:
      - /tmp/
    source:
      - /community/projects/build-output/bzt17-bundle.zip
      - /community/projects/build-output/halloween-bundle.zip
    strip_components: 2

    volumes:
      - /root/.ssh/id_rsa:/ssh/id_rsa


  release:
    group: deploy
    image: appleboy/drone-ssh
    host: faavne.no
    username: root
    key_path: /ssh/id_rsa
    secrets: [ssh_key]
    when:
      event:
        - tag
    script:
      - \cp -f /tmp/halloween-bundle.zip /mnt/nginx-fs/files/bz-community/bz-halloween/bz-halloween_${DRONE_TAG}.zip || true
      - \cp -f /tmp/bzt17-bundle.zip /mnt/nginx-fs/files/bz-community/bzt-2017/bzt17_${DRONE_TAG}.zip || true

